cravattdb:
    build: .
    ports:
        - "8080:5000"
    volumes:
        - .:/home/cravattdb/cravatt-ip2
        - /mnt/cravattdb:/home/cravattdb/cravatt-ip2/cravattdb/uploads
        - ../cimage-minimal:/home/cravattdb/cimage-minimal
    links:
        - postgres
        - rabbitmq
        - redis
    tty: true
    stdin_open: true
postgres:
    image: cravattlab/cravattdb_postgres
    extends:
        file: config/database.yml
        service: database
rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    tty: true
    stdin_open: true
redis:
    image: redis
    hostname: redis
