cravattdb:
    build: .
    ports:
        - '8080:5000'
    environment:
        DEBUG: 'true'
        LC_ALL: 'C.UTF-8'
        LANG: 'C.UTF-8'
        FLASK_APP: 'cravattdb/__init__.py'
    volumes:
        - .:/home/cravattdb/cravattdb
        - /mnt/cravattdb:/home/cravattdb/cravattdb/cravattdb/uploads/processing
        - ../cimage-minimal:/home/cravattdb/cimage-minimal
    links:
        - postgres
        - rabbitmq
        - redis
    tty: true
    stdin_open: true
postgres:
    image: cravattlab/cravattdb_postgres
    extends:
        file: config/secrets.yml
        service: database
rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    tty: true
    stdin_open: true
redis:
    image: redis
    hostname: redis
