"""empty message

Revision ID: 12118a9706f7
Revises: 321971a9085b
Create Date: 2016-07-27 05:55:20.740739

"""

# revision identifiers, used by Alembic.
revision = '12118a9706f7'
down_revision = '321971a9085b'

from alembic import op
import sqlalchemy as sa
from cravattdb.home.models import Experiment


bind = op.get_bind()
has_type = bind.execute(
        "SELECT EXISTS (SELECT 1 FROM pg_type "
        "WHERE typname='quantification_numerator_types')").scalar()
if not has_type:
    bind.execute("CREATE TYPE quantification_numerator_types AS ENUM ('L', 'H')")


def upgrade():
    bind = op.get_bind()
    typ = Experiment.__table__.c.quantification_numerator.type
    typ._on_table_create(Experiment.__table__, bind, checkfirst=True)
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('quantification_numerator', sa.Enum('L', 'H', name='quantification_numerator_types'), nullable=True))
    op.create_index(op.f('ix_experiment_quantification_numerator'), 'experiment', ['quantification_numerator'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_quantification_numerator'), table_name='experiment')
    op.drop_column('experiment', 'quantification_numerator')
    ### end Alembic commands ###
    bind = op.get_bind()
    typ = Experiment.__table__.c.quantification_numerator.type
    typ.drop(bind, checkfirst=True)
