"""empty message

Revision ID: 12118a9706f7
Revises: 321971a9085b
Create Date: 2016-07-27 05:55:20.740739

"""

# revision identifiers, used by Alembic.
revision = '12118a9706f7'
down_revision = '321971a9085b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('quantification_numerator', sa.Enum('L', 'H', name='quantification_numerator_types'), nullable=True))
    op.create_index(op.f('ix_experiment_quantification_numerator'), 'experiment', ['quantification_numerator'], unique=False)
    op.drop_index('ix_experiment_ratio_numerator', table_name='experiment')
    op.drop_column('experiment', 'ratio_numerator')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('ratio_numerator', postgresql.ENUM('L', 'H', name='ratio_numerator_types'), autoincrement=False, nullable=True))
    op.create_index('ix_experiment_ratio_numerator', 'experiment', ['ratio_numerator'], unique=False)
    op.drop_index(op.f('ix_experiment_quantification_numerator'), table_name='experiment')
    op.drop_column('experiment', 'quantification_numerator')
    ### end Alembic commands ###
