"""empty message

Revision ID: 2924c62ff4ed
Revises: f6d3f21335a4
Create Date: 2016-06-12 00:06:09.869495

"""

# revision identifiers, used by Alembic.
revision = '2924c62ff4ed'
down_revision = 'f6d3f21335a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dataset_experiment_id'), 'dataset', ['experiment_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_experiment_id'), table_name='dataset')
    ### end Alembic commands ###
