"""empty message

Revision ID: 321971a9085b
Revises: ceae5950ab73
Create Date: 2016-07-21 19:00:37.029778

"""

# revision identifiers, used by Alembic.
revision = '321971a9085b'
down_revision = 'ceae5950ab73'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.Enum('in vitro', 'in vivo', 'in situ', name='method_types'), nullable=True),
    sa.Column('fraction', sa.Enum('L', 'H', name='fraction_types'), nullable=True),
    sa.Column('time', sa.Numeric(), nullable=True),
    sa.Column('concentration', sa.Numeric(), nullable=True),
    sa.Column('inhibitor_id', sa.Integer(), nullable=True),
    sa.Column('probe_id', sa.Integer(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['inhibitor_id'], ['inhibitor.id'], ),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_experiment_id'), 'treatment', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_treatment_fraction'), 'treatment', ['fraction'], unique=False)
    op.create_index(op.f('ix_treatment_inhibitor_id'), 'treatment', ['inhibitor_id'], unique=False)
    op.create_index(op.f('ix_treatment_method'), 'treatment', ['method'], unique=False)
    op.create_index(op.f('ix_treatment_probe_id'), 'treatment', ['probe_id'], unique=False)
    op.drop_constraint('experiment_treatment_type_id_fkey', 'experiment', type_='foreignkey')
    op.drop_index('ix_experiment_treatment_type_id', table_name='experiment')
    op.drop_column('experiment', 'treatment_type_id')
    op.drop_column('experiment', 'treatment')
    op.drop_table('treatment_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('treatment', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('treatment_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('experiment_treatment_type_id_fkey', 'experiment', 'treatment_type', ['treatment_type_id'], ['id'])
    op.create_index('ix_experiment_treatment_type_id', 'experiment', ['treatment_type_id'], unique=False)
    op.create_table('treatment_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='treatment_type_pkey')
    )
    op.drop_index(op.f('ix_treatment_probe_id'), table_name='treatment')
    op.drop_index(op.f('ix_treatment_method'), table_name='treatment')
    op.drop_index(op.f('ix_treatment_inhibitor_id'), table_name='treatment')
    op.drop_index(op.f('ix_treatment_fraction'), table_name='treatment')
    op.drop_index(op.f('ix_treatment_experiment_id'), table_name='treatment')
    op.drop_table('treatment')
    ### end Alembic commands ###
