"""empty message

Revision ID: 438d968deb2f
Revises: 7eeca573ddc0
Create Date: 2016-06-13 19:13:52.358964

"""

# revision identifiers, used by Alembic.
revision = '438d968deb2f'
down_revision = '7eeca573ddc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proteomic_fraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proteomic_fraction_description'), 'proteomic_fraction', ['description'], unique=False)
    op.create_index(op.f('ix_proteomic_fraction_name'), 'proteomic_fraction', ['name'], unique=False)
    op.add_column('experiment', sa.Column('proteomic_fraction_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experiment_proteomic_fraction_id'), 'experiment', ['proteomic_fraction_id'], unique=False)
    op.create_foreign_key(None, 'experiment', 'proteomic_fraction', ['proteomic_fraction_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_index(op.f('ix_experiment_proteomic_fraction_id'), table_name='experiment')
    op.drop_column('experiment', 'proteomic_fraction_id')
    op.drop_index(op.f('ix_proteomic_fraction_name'), table_name='proteomic_fraction')
    op.drop_index(op.f('ix_proteomic_fraction_description'), table_name='proteomic_fraction')
    op.drop_table('proteomic_fraction')
    ### end Alembic commands ###
