"""empty message

Revision ID: 4bbd7ff1099a
Revises: aae17dd707fd
Create Date: 2016-08-12 01:08:54.257215

"""

# revision identifiers, used by Alembic.
revision = '4bbd7ff1099a'
down_revision = 'aae17dd707fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('dataset_symbol_lower_text_idx', 'dataset', [text('lower(symbol) text_pattern_ops')], unique=False),
    op.create_index('dataset_description_gin_idx', 'dataset', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('dataset_symbol_lower_text_idx', table_name='dataset')
    op.drop_index('dataset_description_gin_idx', table_name='dataset')
    ### end Alembic commands ###
