"""empty message

Revision ID: 6e6ea3467ed2
Revises: d56c4ebf3684
Create Date: 2016-07-06 17:55:51.989987

"""

# revision identifiers, used by Alembic.
revision = '6e6ea3467ed2'
down_revision = 'd56c4ebf3684'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism', sa.Column('scientific_name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_organism_scientific_name'), 'organism', ['scientific_name'], unique=True)
    op.drop_index('ix_organism_display_name', table_name='organism')
    op.drop_column('organism', 'display_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism', sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_organism_display_name', 'organism', ['display_name'], unique=True)
    op.drop_index(op.f('ix_organism_scientific_name'), table_name='organism')
    op.drop_column('organism', 'scientific_name')
    ### end Alembic commands ###
