"""empty message

Revision ID: 7eeca573ddc0
Revises: 2924c62ff4ed
Create Date: 2016-06-13 04:08:08.873995

"""

# revision identifiers, used by Alembic.
revision = '7eeca573ddc0'
down_revision = '2924c62ff4ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell_line')
    op.add_column('experiment', sa.Column('cell_type_id', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('experiment', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('experiment', sa.Column('sample_type_id', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('treatment_details', postgresql.JSONB(), nullable=True))
    op.add_column('experiment', sa.Column('treatment_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experiment_cell_type_id'), 'experiment', ['cell_type_id'], unique=False)
    op.create_index(op.f('ix_experiment_experiment_type_id'), 'experiment', ['experiment_type_id'], unique=False)
    op.create_index(op.f('ix_experiment_inhibitor_id'), 'experiment', ['inhibitor_id'], unique=False)
    op.create_index(op.f('ix_experiment_instrument_id'), 'experiment', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_experiment_organism_id'), 'experiment', ['organism_id'], unique=False)
    op.create_index(op.f('ix_experiment_probe_id'), 'experiment', ['probe_id'], unique=False)
    op.create_index(op.f('ix_experiment_sample_type_id'), 'experiment', ['sample_type_id'], unique=False)
    op.create_index(op.f('ix_experiment_treatment_type_id'), 'experiment', ['treatment_type_id'], unique=False)
    op.create_index(op.f('ix_experiment_user_id'), 'experiment', ['user_id'], unique=False)
    op.create_foreign_key(None, 'experiment', 'instrument', ['instrument_id'], ['id'])
    op.create_foreign_key(None, 'experiment', 'treatment_type', ['treatment_type_id'], ['id'])
    op.create_foreign_key(None, 'experiment', 'cell_type', ['cell_type_id'], ['id'])
    op.create_foreign_key(None, 'experiment', 'sample_type', ['sample_type_id'], ['id'])
    op.create_index(op.f('ix_cell_type_name'), 'cell_type', ['name'], unique=False)
    op.create_index(op.f('ix_experiment_type_name'), 'experiment_type', ['name'], unique=False)
    op.create_index(op.f('ix_inhibitor_inchi'), 'inhibitor', ['inchi'], unique=False)
    op.create_index(op.f('ix_inhibitor_iupac_name'), 'inhibitor', ['iupac_name'], unique=False)
    op.create_index(op.f('ix_inhibitor_name'), 'inhibitor', ['name'], unique=False)
    op.create_index(op.f('ix_instrument_name'), 'instrument', ['name'], unique=False)
    op.create_index(op.f('ix_organism_display_name'), 'organism', ['display_name'], unique=False)
    op.create_index(op.f('ix_organism_name'), 'organism', ['name'], unique=False)
    op.create_index(op.f('ix_probe_inchi'), 'probe', ['inchi'], unique=False)
    op.create_index(op.f('ix_probe_iupac_name'), 'probe', ['iupac_name'], unique=False)
    op.create_index(op.f('ix_probe_name'), 'probe', ['name'], unique=False)
    op.create_index(op.f('ix_treatment_type_name'), 'treatment_type', ['name'], unique=False)
    op.add_column('cell_type', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('sample_type', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('treatment_type', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_sample_type_name'), 'sample_type', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_type_name'), table_name='sample_type')
    op.drop_column('treatment_type', 'description')
    op.drop_column('sample_type', 'description')
    op.drop_column('cell_type', 'description')
    op.drop_index(op.f('ix_treatment_type_name'), table_name='treatment_type')
    op.drop_index(op.f('ix_probe_name'), table_name='probe')
    op.drop_index(op.f('ix_probe_iupac_name'), table_name='probe')
    op.drop_index(op.f('ix_probe_inchi'), table_name='probe')
    op.drop_index(op.f('ix_organism_name'), table_name='organism')
    op.drop_index(op.f('ix_organism_display_name'), table_name='organism')
    op.drop_index(op.f('ix_instrument_name'), table_name='instrument')
    op.drop_index(op.f('ix_inhibitor_name'), table_name='inhibitor')
    op.drop_index(op.f('ix_inhibitor_iupac_name'), table_name='inhibitor')
    op.drop_index(op.f('ix_inhibitor_inchi'), table_name='inhibitor')
    op.drop_index(op.f('ix_experiment_type_name'), table_name='experiment_type')
    op.drop_index(op.f('ix_cell_type_name'), table_name='cell_type')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_index(op.f('ix_experiment_user_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_treatment_type_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_sample_type_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_probe_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_organism_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_instrument_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_inhibitor_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_experiment_type_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_cell_type_id'), table_name='experiment')
    op.drop_column('experiment', 'treatment_type_id')
    op.drop_column('experiment', 'treatment_details')
    op.drop_column('experiment', 'sample_type_id')
    op.drop_column('experiment', 'modified')
    op.drop_column('experiment', 'instrument_id')
    op.drop_column('experiment', 'description')
    op.drop_column('experiment', 'cell_type_id')
    op.create_table('cell_line',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('synonyms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cell_line_pkey')
    )
    ### end Alembic commands ###
