"""empty message

Revision ID: aae17dd707fd
Revises: 8b195c2e0150
Create Date: 2016-08-03 20:32:47.214262

"""

# revision identifiers, used by Alembic.
revision = 'aae17dd707fd'
down_revision = '8b195c2e0150'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'residue_number',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'residue_number',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    ### end Alembic commands ###
