"""empty message

Revision ID: ceae5950ab73
Revises: 6e6ea3467ed2
Create Date: 2016-07-21 04:19:13.022359

"""

# revision identifiers, used by Alembic.
revision = 'ceae5950ab73'
down_revision = '6e6ea3467ed2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cell_type_description'), 'cell_type', ['description'], unique=False)
    op.add_column('experiment', sa.Column('quant_params', postgresql.JSONB(), nullable=True))
    op.add_column('experiment', sa.Column('search_params', postgresql.JSONB(), nullable=True))
    op.add_column('experiment', sa.Column('treatment', postgresql.JSONB(), nullable=True))
    op.drop_index('ix_experiment_inhibitor_id', table_name='experiment')
    op.drop_index('ix_experiment_probe_id', table_name='experiment')
    op.drop_constraint('experiment_inhibitor_id_fkey', 'experiment', type_='foreignkey')
    op.drop_constraint('experiment_probe_id_fkey', 'experiment', type_='foreignkey')
    op.drop_column('experiment', 'treatment_details')
    op.drop_column('experiment', 'additional_search_params')
    op.drop_column('experiment', 'probe_id')
    op.drop_column('experiment', 'additional_quant_params')
    op.drop_column('experiment', 'inhibitor_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('inhibitor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('additional_quant_params', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('probe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('additional_search_params', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('treatment_details', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.create_foreign_key('experiment_probe_id_fkey', 'experiment', 'probe', ['probe_id'], ['id'])
    op.create_foreign_key('experiment_inhibitor_id_fkey', 'experiment', 'inhibitor', ['inhibitor_id'], ['id'])
    op.create_index('ix_experiment_probe_id', 'experiment', ['probe_id'], unique=False)
    op.create_index('ix_experiment_inhibitor_id', 'experiment', ['inhibitor_id'], unique=False)
    op.drop_column('experiment', 'treatment')
    op.drop_column('experiment', 'search_params')
    op.drop_column('experiment', 'quant_params')
    op.drop_index(op.f('ix_cell_type_description'), table_name='cell_type')
    ### end Alembic commands ###
