"""empty message

Revision ID: d56c4ebf3684
Revises: b58403c860b5
Create Date: 2016-06-21 18:16:43.092462

"""

# revision identifiers, used by Alembic.
revision = 'd56c4ebf3684'
down_revision = 'b58403c860b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('inverse_ratio_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experiment_inverse_ratio_id'), 'experiment', ['inverse_ratio_id'], unique=False)
    op.create_foreign_key(None, 'experiment', 'experiment', ['inverse_ratio_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_index(op.f('ix_experiment_inverse_ratio_id'), table_name='experiment')
    op.drop_column('experiment', 'inverse_ratio_id')
    ### end Alembic commands ###
