"""empty message

Revision ID: fb445e98c6cc
Revises: 314830701cac
Create Date: 2016-06-14 23:46:45.483739

"""

# revision identifiers, used by Alembic.
revision = 'fb445e98c6cc'
down_revision = '314830701cac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cell_type_name', table_name='cell_type')
    op.create_index(op.f('ix_cell_type_name'), 'cell_type', ['name'], unique=True)
    op.drop_index('ix_experiment_type_name', table_name='experiment_type')
    op.create_index(op.f('ix_experiment_type_name'), 'experiment_type', ['name'], unique=True)
    op.drop_index('ix_inhibitor_inchi', table_name='inhibitor')
    op.create_index(op.f('ix_inhibitor_inchi'), 'inhibitor', ['inchi'], unique=True)
    op.drop_index('ix_inhibitor_iupac_name', table_name='inhibitor')
    op.create_index(op.f('ix_inhibitor_iupac_name'), 'inhibitor', ['iupac_name'], unique=True)
    op.drop_index('ix_inhibitor_name', table_name='inhibitor')
    op.create_index(op.f('ix_inhibitor_name'), 'inhibitor', ['name'], unique=True)
    op.drop_index('ix_instrument_name', table_name='instrument')
    op.create_index(op.f('ix_instrument_name'), 'instrument', ['name'], unique=True)
    op.drop_index('ix_organism_display_name', table_name='organism')
    op.create_index(op.f('ix_organism_display_name'), 'organism', ['display_name'], unique=True)
    op.drop_index('ix_organism_name', table_name='organism')
    op.create_index(op.f('ix_organism_name'), 'organism', ['name'], unique=True)
    op.create_unique_constraint(None, 'organism', ['tax_id'])
    op.drop_index('ix_probe_inchi', table_name='probe')
    op.create_index(op.f('ix_probe_inchi'), 'probe', ['inchi'], unique=True)
    op.drop_index('ix_probe_iupac_name', table_name='probe')
    op.create_index(op.f('ix_probe_iupac_name'), 'probe', ['iupac_name'], unique=True)
    op.drop_index('ix_probe_name', table_name='probe')
    op.create_index(op.f('ix_probe_name'), 'probe', ['name'], unique=True)
    op.drop_index('ix_proteomic_fraction_name', table_name='proteomic_fraction')
    op.create_index(op.f('ix_proteomic_fraction_name'), 'proteomic_fraction', ['name'], unique=True)
    op.drop_index('ix_sample_type_name', table_name='sample_type')
    op.create_index(op.f('ix_sample_type_name'), 'sample_type', ['name'], unique=True)
    op.drop_index('ix_treatment_type_name', table_name='treatment_type')
    op.create_index(op.f('ix_treatment_type_name'), 'treatment_type', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_type_name'), table_name='treatment_type')
    op.create_index('ix_treatment_type_name', 'treatment_type', ['name'], unique=False)
    op.drop_index(op.f('ix_sample_type_name'), table_name='sample_type')
    op.create_index('ix_sample_type_name', 'sample_type', ['name'], unique=False)
    op.drop_index(op.f('ix_proteomic_fraction_name'), table_name='proteomic_fraction')
    op.create_index('ix_proteomic_fraction_name', 'proteomic_fraction', ['name'], unique=False)
    op.drop_index(op.f('ix_probe_name'), table_name='probe')
    op.create_index('ix_probe_name', 'probe', ['name'], unique=False)
    op.drop_index(op.f('ix_probe_iupac_name'), table_name='probe')
    op.create_index('ix_probe_iupac_name', 'probe', ['iupac_name'], unique=False)
    op.drop_index(op.f('ix_probe_inchi'), table_name='probe')
    op.create_index('ix_probe_inchi', 'probe', ['inchi'], unique=False)
    op.drop_constraint(None, 'organism', type_='unique')
    op.drop_index(op.f('ix_organism_name'), table_name='organism')
    op.create_index('ix_organism_name', 'organism', ['name'], unique=False)
    op.drop_index(op.f('ix_organism_display_name'), table_name='organism')
    op.create_index('ix_organism_display_name', 'organism', ['display_name'], unique=False)
    op.drop_index(op.f('ix_instrument_name'), table_name='instrument')
    op.create_index('ix_instrument_name', 'instrument', ['name'], unique=False)
    op.drop_index(op.f('ix_inhibitor_name'), table_name='inhibitor')
    op.create_index('ix_inhibitor_name', 'inhibitor', ['name'], unique=False)
    op.drop_index(op.f('ix_inhibitor_iupac_name'), table_name='inhibitor')
    op.create_index('ix_inhibitor_iupac_name', 'inhibitor', ['iupac_name'], unique=False)
    op.drop_index(op.f('ix_inhibitor_inchi'), table_name='inhibitor')
    op.create_index('ix_inhibitor_inchi', 'inhibitor', ['inchi'], unique=False)
    op.drop_index(op.f('ix_experiment_type_name'), table_name='experiment_type')
    op.create_index('ix_experiment_type_name', 'experiment_type', ['name'], unique=False)
    op.drop_index(op.f('ix_cell_type_name'), table_name='cell_type')
    op.create_index('ix_cell_type_name', 'cell_type', ['name'], unique=False)
    ### end Alembic commands ###
