version: '2'

# nested so that it can be consumed by docker directly
services:
  database:
    environment:
        POSTGRES_PASSWORD: 'rZTkh5lD8LmfrepUf7Jq'
        DB_USER: 'cravattdb'
        DB_PASS: 'B6kVrq4rTPEcNnju39WF'
        DB_NAME: 'cravattdb'
  flask:
    environment:
      SECRET_KEY: 'dbkOT1o!MVp7ucsRnuaL'
  flask-security:
    environment:
      SECURITY_PASSWORD_SALT: '8CjvYzVZgV8q:ZL#,7R8'
      SECURITY_LDAP_BIND_DN: 'example@lj.scripps.edu'
      SECURITY_LDAP_BIND_PASSWORD: 'password'
  mail:
    environment:
      EMAIL: 'mail@example.com'
      EMAIL_PASSWORD: 'password'