database:
  # nested so that it can be consumed by docker directly
  environment:
      POSTGRES_PASSWORD: 'rZTkh5lD8LmfrepUf7Jq'
      DB_USER: 'cravattdb'
      DB_PASS: 'B6kVrq4rTPEcNnju39WF'
      DB_NAME: 'cravattdb'
flask:
  SECRET_KEY: 'dbkOT1o!MVp7ucsRnuaL'
flask-security:
  SECURITY_PASSWORD_SALT: '8CjvYzVZgV8q:ZL#,7R8'
mail:
  EMAIL: 'mail@example.com'
  EMAIL_PASSWORD: 'password'